class Simplify:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SimplifyPreserveTopology:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SimplifyVW:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
