#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["psycopg[binary]>=3.2"]
# ///
"""Generate `rust/geodatafusion/src/util/srid_authorities.rs` from PostGIS's `spatial_ref_sys`.

PostGIS SRIDs equal their authority code, and each SRID belongs to one authority (EPSG or
ESRI, plus a few others). The generated file lists the contiguous SRID ranges per authority, so
`util::srid` can turn an SRID into the right `AUTHORITY:CODE` CRS without a PROJ database.

Usage:
    dev/postgis.sh start
    uv run dev/generate_srid_authorities.py
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import psycopg

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "rust/geodatafusion/src/util/srid_authorities.rs"
DEFAULT_URL = "postgresql://postgres:postgres@localhost:54329/postgres"

QUERY = """
WITH ranked AS (
    SELECT auth_name, srid, srid - row_number() OVER (PARTITION BY auth_name ORDER BY srid) AS run
    FROM spatial_ref_sys
    WHERE auth_name IN ('EPSG', 'ESRI') AND srid = auth_srid
)
SELECT auth_name, min(srid), max(srid)
FROM ranked
GROUP BY auth_name, run
ORDER BY min(srid)
"""


def main() -> int:
    url = os.environ.get("POSTGIS_URL", DEFAULT_URL)
    with psycopg.connect(url) as conn:
        version = conn.execute("SELECT postgis_lib_version()").fetchone()[0]
        ranges = conn.execute(QUERY).fetchall()

    lines = [
        "//! SRID ranges per authority, from PostGIS's `spatial_ref_sys`.",
        "//!",
        f"//! Generated by `dev/generate_srid_authorities.py` from PostGIS {version}. Don't edit by hand.",
        "",
        "use crate::util::srid::Authority;",
        "",
        "/// Contiguous, sorted, non-overlapping `(first, last, authority)` SRID ranges.",
        "pub(crate) const SRID_AUTHORITIES: &[(i32, i32, Authority)] = &[",
    ]
    for auth_name, first, last in ranges:
        authority = {"EPSG": "Authority::Epsg", "ESRI": "Authority::Esri"}[auth_name]
        lines.append(f"    ({first}, {last}, {authority}),")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    subprocess.run(["rustfmt", "--edition", "2024", str(OUT)], check=False)
    print(f"Wrote {len(ranges)} ranges to {OUT.relative_to(REPO)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
