class Affine:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Translate:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
