class Affine:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Translate:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Scale:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Rotate:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class RotateX:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class RotateY:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class RotateZ:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
