class Collect:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class CollectAgg:
    def __init__(self) -> None: ...
    def __datafusion_aggregate_udf__(self) -> object: ...

class MakeLine:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakeLineAgg:
    def __init__(self) -> None: ...
    def __datafusion_aggregate_udf__(self) -> object: ...

class Point:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointZ:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointZM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakePoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakePointM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakeEnvelope:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
