class Point:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointZ:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointZM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakePoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MakePointM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
