class FlipCoordinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SwapOrdinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force2D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force3DZ:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force3DM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force4D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class ShiftLongitude:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Reverse:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class ForcePolygonCW:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class ForcePolygonCCW:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SnapToGrid:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class QuantizeCoordinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Multi:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class ForceCollection:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class CollectionExtract:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class CollectionHomogenize:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Project:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AddPoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SetPoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class RemovePoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class RemoveRepeatedPoints:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Segmentize:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
