class FlipCoordinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SwapOrdinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force2D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force3DZ:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force3DM:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Force4D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
