class FlipCoordinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SwapOrdinates:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
