class AsBinary:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsEWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsHEXEWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsEWKT:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromEWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromEWKT:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Box2DFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class LineFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PolygonFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MPointFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MLineFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MPolyFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomCollFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class LineFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PolyFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MPointFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MLineFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class MPolyFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomCollFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsGeoJSON:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromGeoJSON:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
