class AsBinary:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsEWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsHEXEWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsEWKT:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AsText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromEWKB:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromEWKT:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromText:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class PointFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeomFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Box2DFromGeoHash:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
