class LineInterpolatePoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class LineInterpolatePoint3D:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class LineInterpolatePoints:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class LineSubstring:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class AddMeasure:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class InterpolatePoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
