class GeometryAbove:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryBelow:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryContains:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryDistanceBox:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryLeft:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryOverAbove:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryOverBelow:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryOverLeft:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryOverRight:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryOverlaps:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryOverlapsNd:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryRight:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometrySame:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryWithin:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
