class SetSRID:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class SRID:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
