[package]
name = "geodatafusion"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Spatial extensions for Apache DataFusion"
categories = { workspace = true }
rust-version = { workspace = true }


[features]
# Enables GEOS-backed UDFs.
# We only use explicitly versioned flags,
# and the structure should be recursive
# (with higher version targets implying lower version ones
# in a chain.)
geos-3_11 = ["dep:geos", "geos/v3_11_0"]

[dependencies]
arrow-arith = { workspace = true }
arrow-array = { workspace = true }
arrow-buffer = { workspace = true }
arrow-schema = { workspace = true }
datafusion = { workspace = true }
datafusion-doc = { workspace = true }
datafusion-macros = { workspace = true }
geo = { workspace = true }
geo-traits = { workspace = true }
geoarrow-array = { workspace = true }
geoarrow-expr-geo = { workspace = true }
geoarrow-schema = { workspace = true }
geohash = { workspace = true }
geos = { workspace = true, optional = true }
thiserror = { workspace = true }
wkt = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
async-trait = { workspace = true }
# The sqllogictests run arbitrary PostGIS-flavoured SQL, so enable the full built-in function set.
datafusion = { workspace = true, features = [
    "sql",
    "nested_expressions",
    "crypto_expressions",
    "datetime_expressions",
    "encoding_expressions",
    "math_expressions",
    "regex_expressions",
    "string_expressions",
    "unicode_expressions",
] }
futures = { workspace = true }
geo-traits = { workspace = true }
geoarrow-array = { workspace = true, features = ["test-data"] }
geoarrow-schema = { workspace = true }
object_store = { workspace = true, features = ["http"] }
sqllogictest = { workspace = true }
tokio = { workspace = true, features = ["macros", "fs", "rt-multi-thread"] }
tokio-postgres = { workspace = true }
wkb = { workspace = true }

[[test]]
name = "sqllogictests"
path = "tests/sqllogictests/main.rs"
harness = false

[package.metadata.docs.rs]
all-features = true
